weights: ''''''
cfg: ./models/yolov4-csp.yaml
data: E:/My Drive/All-My-Projects/Gun Detector Yolov4/ScaledYOLOv4/data/coco.yaml
hyp: data/hyp.finetune.yaml
epochs: 100
batch_size: 16
img_size:
- 416
- 416
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
name: yolov4-csp-results
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
total_batch_size: 16
world_size: 1
global_rank: -1
